[tool.pytest.ini_options]
pythonpath = ["src",]
testpaths = ["tests",]
asyncio_mode = "auto"
# addopts = "--cov-config=.coveragerc --cov=. --cov-report xml:cov.xml -"

[tool.flake8]
max-line-length = 120