[tool.pytest.ini_options]
pythonpath = ["src",]
testpaths = ["tests",]
asyncio_mode = "auto"
# addopts = "--cov-config=./tests/.coveragerc --cov=. --cov-report xml:cov.xml"

[tool.flake8]
max-line-length = 120

[tool.black]
line-length = 120
target-version = ['py310']